s=set()
s1=input("Enter Number 1: ")
s.add(int(s1))
s2=input("Enter Number 2: ")
s.add(int(s2))
s3=input("Enter Number 3: ")
s.add(int(s3))
s4=input("Enter Number 4: ")
s.add(int(s4))
s5=input("Enter Number 5: ")
s.add(int(s5))
s6=input("Enter Number 6: ")
s.add(int(s6))
s7=input("Enter Number 7: ")
s.add(int(s7))
s8=input("Enter Number 8: ")
s.add(int(s8))

print("The unique numbers are: ",s)